apiVersion: apps/v1
kind: Deployment
metadata:
  name: biosfera-deployment
  labels:
    app: biosfera
spec:
  replicas: 2
  selector:
    matchLabels:
      app: biosfera
  template:
    metadata:
      labels:
        app: biosfera
    spec:
      containers:
      - name: biosfera
        image: marioraulino/biosfera:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: biosfera-service
spec:
  selector:
    app: biosfera
  ports:
  - name: biosfera-port
    protocol: TCP
    port: 80
